-- Phase 3: URL shortening table
--
-- short_code is derived from the record's numeric id via Base62 encoding.
-- It is stored redundantly for fast lookup without re-computing the encoding.
-- original_url length 2048 covers the practical maximum for all major browsers.

CREATE TABLE urls (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    short_code VARCHAR(12) NOT NULL,
    status     VARCHAR(32) NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    updated_at TIMESTAMP   NOT NULL,
    CONSTRAINT uk_urls_short_code UNIQUE (short_code),
    CONSTRAINT fk_urls_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_urls_user_id   ON urls (user_id);
