-- Phase 7: Click analytics table
--
-- event_id is a unique UUID generated by the click event producer for idempotency.
-- Foreign key to urls cascades on delete when a URL record is removed.

CREATE TABLE click_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    VARCHAR(36) NOT NULL,
    url_id      BIGINT      NOT NULL,
    short_code  VARCHAR(12) NOT NULL,
    user_id     BIGINT      NOT NULL,
    occurred_at TIMESTAMP   NOT NULL,
    CONSTRAINT uk_click_events_event_id UNIQUE (event_id),
    CONSTRAINT fk_click_events_url FOREIGN KEY (url_id) REFERENCES urls (id) ON DELETE CASCADE
);

CREATE INDEX idx_click_events_url_id ON click_events (url_id);
CREATE INDEX idx_click_events_short_code ON click_events (short_code);
CREATE INDEX idx_click_events_occurred_at ON click_events (occurred_at);
CREATE INDEX idx_click_events_url_occurred ON click_events (url_id, occurred_at DESC);
