package com.slicelink.urls;

import com.slicelink.users.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.Instant;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * Persistent URL record.
 *
 * <p>The primary key is assigned by the application via {@link UrlIdGenerator}
 * (not auto-incremented by the database) so that the ID is known before the
 * INSERT and can immediately be Base62-encoded into the short code within the
 * same transaction.
 */
@Entity
@Table(name = "urls")
public class Url {

    /**
     * Application-assigned identifier generated by {@link UrlIdGenerator}.
     * Uses {@code @Id} without {@code @GeneratedValue} — the service sets it
     * explicitly before saving.
     */
    @Id
    @Column(nullable = false, updatable = false)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false, updatable = false)
    private User user;

    @Column(name = "original_url", nullable = false, length = 2048)
    private String originalUrl;

    /**
     * Short code derived from {@code id} via Base62 encoding.
     * Stored for fast lookup; must match {@code Base62.encode(id)}.
     */
    @Column(name = "short_code", nullable = false, unique = true, length = 12,
            updatable = false)
    private String shortCode;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 32)
    private UrlStatus status;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    protected Url() { }

    public Url(Long id, User user, String originalUrl, String shortCode, UrlStatus status) {
        this.id          = id;
        this.user        = user;
        this.originalUrl = originalUrl;
        this.shortCode   = shortCode;
        this.status      = status;
    }

    // ── accessors & mutators ────────────────────────────────────────────────

    public Long      getId()          { return id;          }
    public User      getUser()        { return user;        }
    public String    getOriginalUrl() { return originalUrl; }
    public String    getShortCode()   { return shortCode;   }
    public UrlStatus getStatus()      { return status;      }
    public Instant   getCreatedAt()   { return createdAt;   }
    public Instant   getUpdatedAt()   { return updatedAt;   }

    public void updateOriginalUrl(String originalUrl) {
        this.originalUrl = originalUrl;
    }

    public void updateStatus(UrlStatus status) {
        this.status = status;
    }
}
